### ISSUE TITLE
Tabs don't work on specific page

### ISSUE THREAD

**Issue by mitchellknight** [Ultimate-Blocks/Ultimate-Blocks#14] opened 2020-09-02 21:05 UTC
I use the Tabs block on two pages on my website. They're used in the same way (they have embedded videos from YouTube and Vimeo in different a few tabs.) On one page it works, on the other it doesn't.

When I check my browser console I see the following:

```
Uncaught TypeError: Cannot read property 'classList' of null
    at ub_handleTabEvent (front.build.js?ver=2.3.9:34)
    at HTMLDivElement.<anonymous> (front.build.js?ver=2.3.9:104)
```

Any idea what's causing this or how to fix it?

**Comment by Alexius08** [comment] 2020-09-03 03:40
Hi @mitchellknight! Can you share a link to the page where this happens? We're unable to recreate the issue on our end.

**Comment by mitchellknight** [comment] 2020-09-03 19:42
The issue happens on `https://staging[dot]apexprocare[dot]com` (Sorry, trying to keep this staging site off Google.) Check near the bottom of the page above the embedded video. The tab controls are styled like buttons (with CSS) but it's actually using the Tab block.

**Comment by Alexius08** [comment] 2020-09-04 14:10
Upon checking the linked page, I noticed that some of the tabbed content block's class names have the wrong value after enabling either "align wide" or "align full" for the block. I've been able to reproduce the bug after using either of those settings on my end.

A typo in one of the plugin files turns out to be the cause of this issue, and two class names are somehow merged when they're supposed to be separate instead. [The fix](https://github.com/Ultimate-Blocks/Ultimate-Blocks/commit/f9aaafe9df3981317987114f6ad15cb15866f928#diff-b79486820fc7685d6522b4434a1fc00b) is now available here in our Github repository and will be included in the Wordpress plugin directory when the new version is out.

If you want to have the fix before the new version is released, you can [save this file](https://raw.githubusercontent.com/Ultimate-Blocks/Ultimate-Blocks/f9aaafe9df3981317987114f6ad15cb15866f928/src/blocks/tabbed-content/block.php) as block.php, go to the plugin folder, navigate to src/blocks/tabbed-content/ , and overwrite the existing block.php file with the one you just downloaded.

Please let us know how it goes.

**Comment by mitchellknight** [comment] 2020-09-04 15:25
Awesome! I can confirm that replacing the `src/blocks/tabbed-content/block.php` with the new version fixed the issue on my website.

**Comment by Alexius08** [comment] 2020-09-04 16:03
Great! Glad to know it worked.

**Closed as completed by Alexius08** 2020-09-04 16:03 UTC
